var paper = [
{
"title": "QPR.JS: A Runtime Framework for QoS-Aware Power",
"abbr": "ISLPED-Poster '14",
"category": "conference",
"authors": "Wonjun Lee, Channoh Kim, and Jae W. Lee",
"conference": "IEEE/ACM International Symposium on Low Power Electronics and Design",
"place": "La Jolla, California",
"date": "August 2014",
"pdf": "pubs/islped14_qprjs.pdf",
"remark": "<span style=\"font-weight:bold; font-style:italic; color: #FF0033\">It's test!</span>",
"team": "pjs",
"selected": true
},
{
"title": "eDRAM-Based Tiered-Reliability Memory with Applications to Low Power Frame Buffers",
"abbr": "ISLPED '14",
"category": "conference",
"authors": "Kyungsang Cho, Yongjun Lee, Younghwan Oh, Gyoo-Cheol Hwang, and Jae W. Lee",
"conference": "IEEE/ACM International Symposium on Low Power Electronics and Design",
"place": "La Jolla, California",
"date": "August 2014",
"pdf": "pubs/islped14_trm.pdf",
"remark": "",
"team": "uncore",
"selected": true
},
{
"title": "RIGHT: An HTML Canvas and JavaScript-based Interactive Data Visualization Package for Linked Graphics",
"abbr": "UseR!-Poster '14",
"category": "conference",
"authors": "ChungHa Sung, JongHyun Bae, SangGi Hong, TaeJoon Song, Jae W. Lee, and Junghoon Lee",
"conference": "The R User Conference",
"place": "Los Angeles, California",
"date": "July 2014",
"pdf": "pubs/user14_right.pdf",
"remark": "",
"team": "",
"selected": false
},
{
"title": "Automatic Runtime Selection of Best Hardware for Data-Parallel JavaScript Kernels via Lifelong Profiling",
"abbr": "PRISM-2",
"category": "workshop",
"authors": "Younghwan Oh, Xianglan Piao, Channoh Kim, and Jae W. Lee",
"conference": "2nd International Workshop on Parallelism in Mobile Platforms",
"place": "Minneapolis, Minnesota",
"date": "June 2014",
"pdf": "pubs/prism14_cgce.pdf",
"remark": "(in conjunction with the ISCA-41)",
"team": "pjs",
"selected": false
},
{
"title": "Efficient CPU-GPU Work Sharing for Data-Parallel JavaScript Workloads",
"abbr": "WWW-Poster '14",
"category": "conference",
"authors": "Xianglan Piao, Channoh Kim, Younghwan Oh, Hanjun Kim, and Jae W. Lee",
"conference": "23rd International World Wide Web Conference",
"place": "Seoul, Korea",
"date": "May 2014",
"pdf": "pubs/www14_jaws.pdf",
"remark": "",
"team": "pjs",
"selected": true
},
{
"title": "Hardware Acceleration of Sparse Matrix-Vector Multiply",
"abbr": "SHAW-5",
"category": "workshop",
"authors": "Bong Jin Ko, Jin Min Kim, Kyungsang Cho, and Jae W. Lee",
"conference": "5th Workshop on SoCs, Heterogeneous Architectures and Workloads",
"place": "Orlando, Florida",
"date": "February 2014",
"pdf": "",
"remark": "(in conjunction with HPCA-20)",
"team": "supercomputing",
"selected": false
},
{
"title": "Optimal Power Allocation for Multiprogrammed Workloads on Single-Chip Heterogeneous Processors",
"abbr": "WEED '13",
"category": "workshop",
"authors": "Euijin Kwon, Jae Young Jang, Jae W. Lee, and Nam Sung Kim",
"conference": "5th Workshop on Energy-Efficient Design",
"place": "Tel-Aviv, Israel",
"date": "July 2013",
"pdf": "pubs/weed13_schp.pdf",
"remark": "(in conjunction with ISCA-40)",
"team": "",
"selected": false
},
{
"title": "An Analytical Model to Predict Performance Impact of DRAM Bank Partitioning",
"abbr": "MSPC '13",
"category": "workshop",
"authors": "Dong Uk Kim, Seokju Yoon, and Jae W. Lee",
"conference": "ACM SIGPLAN Workshop on Memory Systems Performance and Correctness",
"place": "Seattle, Washington",
"date": "July 2013",
"pdf": "http://prof.icc.skku.ac.kr/~jaewlee/pubs/mspc13_bank.pdf",
"remark": "(in conjunction with PLDI 2013)",
"team": "",
"selected": true
},
{
"title": "Practical Speculative Parallelization of Variable-Length Decompression Algorithms",
"abbr": "LCTES '13",
"category": "conference",
"authors": "Hakbeom Jang, Channoh Kim, and Jae W. Lee",
"conference": "Proceedings of the 14th ACM SIGPLAN/SIGBED conference on Languages, compilers and tools for embedded systems",
"place": "Seattle, Washington",
"date": "July 2013",
"pdf": "http://parallel.skku.edu/pubs/lctes13_vld.pdf",
"remark": "",
"team": "",
"selected": true
},
{
"title": "Title",
"abbr": "Abbr",
"category": "Category",
"authors": "Authors",
"conference": "Conference",
"place": "Place",
"date": "January 1970",
"pdf": "pubs/pdf",
"remark": "Remark",
"team": "Team",
"selected": true
}
];
